name: Upload coverage

on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - '!**'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.DEFAULT_NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Set up npm
        run: |
          npm ci

      - name: Exec lint command
        run: |
          npm run lint

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test
          debug: true
